package cs368_projecttwo;


import java.util.*;
import java.awt.Color;
import java.lang.reflect.InvocationTargetException;
import javax.swing.JOptionPane;


/***************************************************************************
 * ViewClass.java
 *
 * This program is used to fincance and plan an individual's retirement.
 * This is the view and controller for this application.
 * 
 * @authors DeVario Voltz, Dan Mikita, Callie O'Brien
 * 
 * @category Computer Science 368
 * @version 2.3
 ***************************************************************************/
public class ViewClass extends javax.swing.JApplet implements Observer {

	//autogenerated serialVersionUID
	private static final long serialVersionUID = -2531844655242885628L;
	
	// creates an instance of the model class to implement MVC
	private ModelClass theModel;


	/***************************************************************************
	 * Initializes the applet ViewClass
	 ***************************************************************************/
	public void init() {
		try {
			java.awt.EventQueue.invokeAndWait(new Runnable() {

				/***************************************************************
				 * Calls the run method to create the view of the applet.
				 ***************************************************************/
				public void run(){
					initComponents();
				}

			});
			
			ModelClass model = new ModelClass();
			theModel = model;
			theModel.addObserver(this);
			
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">  
	/***************************************************************************
	 * This method is called from within the init() method to
	 * initialize the form.
	 * 
	 * This code was autogenerated from NetBeans
	 ***************************************************************************/
	private void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jTextField6 = new javax.swing.JTextField();
		jTextField7 = new javax.swing.JTextField();
		jTextField8 = new javax.swing.JTextField();
		jTextField9 = new javax.swing.JTextField();
		jTextField10 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jComboBox2 = new javax.swing.JComboBox();
		jButton3 = new javax.swing.JButton();
		jSpinner1 = new javax.swing.JSpinner();
		jSpinner2 = new javax.swing.JSpinner();

		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		// setStub(null);

		jTextField1.setToolTipText("Your first and last name.");
		jTextField1.setPreferredSize(new java.awt.Dimension(100, 20));

		jLabel1.setText("Name");

		jLabel2.setText("Age");

		jTextField3.setToolTipText("Your current annual income.");
		jTextField3.setPreferredSize(new java.awt.Dimension(100, 20));

		jLabel3.setText("Annual Income");

		jLabel4.setText("Social Security Income");

		jTextField4.setEditable(false);
		jTextField4.setToolTipText("Income received annually from social security");
		jTextField4.setPreferredSize(new java.awt.Dimension(100, 20));

		jLabel5.setText("Percent of Annual Income Wanted for Retirement");

		jButton1.setText("Calculate");
		jButton1.setToolTipText("Performs the calculations needed to compute annual amount needed to reach your goal.");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Reset");
		jButton2.setToolTipText("Sets all fields to its default value");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jTextField6.setToolTipText("Income received annually from other sources (such as pension plans, earnings on assets, part-time job, etc.)");
		jTextField6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//    jTextField6ActionPerformed(evt);
			}
		});

		jTextField7.setEditable(false);
		jTextField7.setToolTipText("This is how much you need to make up for each retirement year");

		jTextField8.setToolTipText("Total Savings to date (include money accumulated in a 401(k), IRA, or similar retirement plan)");
		jTextField8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//   jTextField8ActionPerformed(evt);
			}
		});

		jTextField9.setEditable(false);
		jTextField9.setToolTipText("The total amount of savings needed when you retire.");

		jTextField10.setEditable(false);
		jTextField10.setToolTipText("Annual amount you'll need to save each year to earn the specified percentage of your income.");

		jLabel6.setText("Other annual income after retirement");

		jLabel7.setText("Annual Retirement funds needed");

		jLabel8.setText("Expected Retirement Age (round up)");

		jLabel9.setText("Life Expectancy (round up)");

		jLabel10.setText("Total Amount In Savings");

		jLabel11.setText("Total Savings Needed at Retirement");

		jLabel12.setText("ANNUAL AMOUNT NEEDED");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "55", "60", "65", "70" }));
		jComboBox1.setToolTipText("Age at which you expect to retire");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "82", "86", "89", "92", "94", "97" }));
		jComboBox2.setToolTipText("Life Expectancy:\n(The average male life expectancy is 89)\n(The average female life expectany is 92)");

		jButton3.setText("Print");
		jButton3.setToolTipText(" Brings up a read-only dialog showing a summary of the resulting plan in a printable form");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jSpinner1.setToolTipText("Your current age.");
		jSpinner1.setValue(30);

		jSpinner2.setToolTipText("The percentage of your current annual income you would like to receive each year during retirement.");
		jSpinner2.setValue(70);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(74, 74, 74)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel3)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jLabel11)
										.addComponent(jLabel12))
										.addComponent(jLabel4)
										.addComponent(jLabel5)
										.addComponent(jLabel2)
										.addComponent(jLabel1)
										.addComponent(jLabel6)
										.addComponent(jLabel7)
										.addComponent(jLabel8)
										.addComponent(jLabel9)
										.addComponent(jLabel10))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																.addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(jTextField6)
																.addComponent(jTextField7)
																.addComponent(jTextField8)
																.addComponent(jTextField9)
																.addComponent(jTextField10)
																.addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
																.addGap(480, 480, 480))
																.addGroup(layout.createSequentialGroup()
																		.addGap(146, 146, 146)
																		.addComponent(jButton1)
																		.addGap(70, 70, 70)
																		.addComponent(jButton2)
																		.addGap(58, 58, 58)
																		.addComponent(jButton3)
																		.addContainerGap(575, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addComponent(jLabel2))
												.addGroup(layout.createSequentialGroup()
														.addGap(31, 31, 31)
														.addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGap(18, 18, 18)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jLabel3)
																.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(18, 18, 18)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(jLabel5)
																		.addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(18, 18, 18)
																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
																				.addGap(18, 18, 18)
																				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(jLabel6))
																						.addGap(25, 25, 25)
																						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																								.addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addComponent(jLabel7))
																								.addGap(18, 18, 18)
																								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(jLabel8))
																										.addGap(18, 18, 18)
																										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(jLabel9))
																												.addGap(18, 18, 18)
																												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(jLabel10))
																														.addGap(16, 16, 16)
																														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																																.addComponent(jLabel11)
																																.addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																																.addGap(55, 55, 55)
																																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																																		.addComponent(jLabel12)
																																		.addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																																		.addGap(34, 34, 34)
																																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																																				.addComponent(jButton1)
																																				.addComponent(jButton2)
																																				.addComponent(jButton3))
																																				.addGap(166, 166, 166))
		);
	}// </editor-fold>

	
	/***************************************************************************
	 * This method handles the event actions performed when the print button
	 * is clicked.
	 ***************************************************************************/
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         

		// TODO add your handling code here:
	}      

	/***************************************************************************
	 * This method handles the event actions performed when the reset button
	 * is clicked. It calls the reset method from theModel class.
	 ***************************************************************************/
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

		theModel.reset();

		
		/**These need to be remove to and used and done with MVC*/
		//jTextField1.setText(theModel.getValue(0));
		//jSpinner1.setValue(theModel.getValue(1));
		jTextField3.setText(theModel.getValue(2));
		//jSpinner2.setValue(theModel.getValue(3));
		jTextField6.setText(theModel.getValue(5));
		jTextField8.setText(theModel.getValue(9));

	}                                        

	/***************************************************************************
	 * This method handles the event actions performed when the calculate 
	 * button is clicked. 
	 * After all the array fields are set according to the data insert in the 
	 * text field the calculate method from the model class is called.
	 ***************************************************************************/
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         

		boolean moveOn = true;
		String errMsg = "The following field(s) are empty: ";
		String errMsgTF1 = "";
		String errMsgTF3 = "";
		String errMsgTF6 = "";
		String errMsgTF7 = "";
		String errMsgTF8 = "";
		String errMsgJS1 = "";
		String errMsgJS2 = "";


		if(jTextField1.getText().length() == 0){
			errMsgTF1 = "\n name; ";
			jTextField1.setBackground(Color.yellow);			
			moveOn = false;			
		}
		else
			theModel.setValue(jTextField1.getText(), 0);


		if(jSpinner1.getValue().toString().length() == 0){
			errMsgJS1 = "\n age; ";
			jSpinner1.setBackground(Color.yellow);
			moveOn = false;			
		}
		else
			theModel.setValue(jSpinner1.getValue().toString(), 1);


		if(jTextField3.getText().length() == 0){
			errMsgTF3 = "\n annual income; ";
			jTextField3.setBackground(Color.yellow);
			moveOn = false;			
		}
		else
			theModel.setValue(jTextField3.getText(), 2);


		if(jSpinner2.getValue().toString().length() == 0){
			errMsgJS2 = "\n percentage of income wanted; ";
			jSpinner2.setBackground(Color.yellow);
			moveOn = false;			
		}
		else
			theModel.setValue(jSpinner2.getValue().toString(), 3);


		if(jTextField6.getText().length() == 0){
			errMsgTF6 = "\n other income; ";
			jTextField6.setBackground(Color.yellow);
			moveOn = false;			
		}
		else
			theModel.setValue(jTextField6.getText(), 5);


		theModel.setValue(jComboBox1.getSelectedItem().toString(), 7);

		theModel.setValue(jComboBox2.getSelectedItem().toString(), 8);


		if(jTextField8.getText().length() == 0){
			errMsgTF8 = "\n amount in savings account; ";
			jTextField8.setBackground(Color.yellow);
			moveOn = false;			
		}
		else
			theModel.setValue(jTextField8.getText(), 9);


		if(moveOn != true)
			JOptionPane.showMessageDialog(
					null,
					errMsg + errMsgTF1 + errMsgTF3 + 
					errMsgTF6 + errMsgTF7 + errMsgTF8 + 
					errMsgJS1 + errMsgJS2 ,
					"Finance Calculator",
					JOptionPane.INFORMATION_MESSAGE);
		else
			theModel.calculate();

	}                                        

	
	/***************************************************************************
	 * This method handles the changes made to the indexes in the array.
	 * When a index is change inside the dataStorage array this method is 
	 * called to update the view of the applet.
	 ***************************************************************************/
	public void update(Observable arg0, Object arg1) {

		jTextField1.setText(theModel.getValue(0));
//		jSpinner1.setValue(theModel.getValue(1));
//		jTextField3.setText(theModel.getValue(2));
//		jSpinner2.setValue(theModel.getValue(3));
//		jTextField6.setText(theModel.getValue(5));
//		jTextField8.setText(theModel.getValue(9));

		jTextField4.setText(theModel.getValue(4));
		jTextField7.setText(theModel.getValue(6));
		jTextField9.setText(theModel.getValue(10));
		jTextField10.setText(theModel.getValue(11));

	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JSpinner jSpinner1;
	private javax.swing.JSpinner jSpinner2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	// End of variables declaration


}
